# Generated by Django 5.2.1 on 2025-05-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruteur',
            name='logo',
            field=models.CharField(default='assets/logo_entreprise.svg', max_length=255),
        ),
    ]
