# Generated by Django 5.2.1 on 2025-06-29 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stage', '0002_alter_annonce_statut_annonce'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.CharField(max_length=255)),
                ('commentaire', models.TextField(blank=True, max_length=1000)),
                ('date_crea', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('resolu', 'resolu'), ('Rejete', 'Rejete')], default='En attente')),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonce', to='stage.annonce')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
