# Generated by Django 5.2.1 on 2025-05-23 23:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creat', models.DateTimeField(default=django.utils.timezone.now)),
                ('titre', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(default='stage professionnel', max_length=255)),
                ('date_limite', models.DateField()),
                ('dure', models.CharField(max_length=50)),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('domaine', models.CharField(max_length=255)),
                ('niveau_etude', models.CharField(max_length=255)),
                ('langue_requises', models.CharField(max_length=255)),
                ('statut_annonce', models.CharField(choices=[('En attente de publication', 'En attente de publication'), ('Publiée', 'Publiée'), ('Expirée', 'Expirée')], default='En attente de publication', max_length=255)),
                ('recruteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.recruteur')),
            ],
        ),
    ]
