# Generated by Django 5.2.1 on 2025-05-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='statut_annonce',
            field=models.CharField(choices=[('En attente de publication', 'En attente de publication'), ('En ligne', 'En ligne'), ('Expirée', 'Expirée')], default='En attente de publication', max_length=255),
        ),
    ]
